version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: comin-time-service
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-comintime}
      - DB_SSL_MODE=disable
      - SERVER_PORT=8080
    networks:
      - comin-network

  postgres:
    image: postgres:16-alpine
    container_name: comin-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-comintime}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - comin-network

networks:
  comin-network:
    driver: bridge

volumes:
  postgres_data: