# .github/workflows/ci.yml
name: CI
on:
  push:
    branches: [dev]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Convert repository owner to lowercase
        id: repo_owner
        run: echo "lowercase_owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ steps.repo_owner.outputs.lowercase_owner }}/comin-time-service:${{ github.sha }}
      
      - name: Update Kubernetes resources
        run: |
          cd k8s/base
          sed -i "s|image: ghcr.io/.*/comin-time-service:.*|image: ghcr.io/${{ steps.repo_owner.outputs.lowercase_owner }}/comin-time-service:${{ github.sha }}|" deployment.yml
      
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add k8s/base/deployment.yml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push